baseURL = 'https://nyuusen.github.io/my-hugo-blog/'
languageCode = 'ja'
title = 'nyuusen blog'
theme = 'PaperMod'

enableRobotsTXT = true
pagination.pagerSize = 20

[params]
env = "production"
author = "nyuusen"
ShowShareButtons = true
ShowReadingTime = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'